services:
  - type: web
    name: pdf-to-excel
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bank_statement_to_excel:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
    plan: free
